version: "2"
plugins:
  eslint:
    enabled: true
  fixme:
    enabled: true
engines:
  duplication:
    exclude_paths:
    - "**/*.test.js"
    - "**/*.e2e.js"
exclude_patterns:
- ".github/"
- ".idea/"
- "dist/"
- "docs/"
- "tools/"
- "vendor/"
- "src/utils/SelectionParser.js"
- "src/utils/MiewCLIParser.js"
