version: "2"
plugins:
  eslint:
    enabled: true
  fixme:
    enabled: true
exclude_patterns:
- ".github/"
- ".idea/"
- "dist/"
- "docs/"
- "tools/"
- "vendor/"
- "src/utils/SelectionParser.js"
- "src/utils/MiewCLIParser.js"
