language: node_js
node_js:
  - "lts/*"
  - "node"
cache:
  yarn: true
  directories:
    - "node_modules"
    - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: "epam"
  ssh_known_hosts:
    - "$DEPLOY_SERVER"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add gulp-cli
  - yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  - gulp
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - sonar-scanner
  - gulp test:coveralls
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
deploy:
  - provider: npm
    skip_cleanup: true
    email: "$NPM_EMAIL"
    api_key: "$NPM_AUTH_TOKEN"
    tag: latest
    on:
      tags: true
      node: "node"
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
  - provider: script
    skip_cleanup: true
    script: "chmod +x ./tools/deploy.sh && ./tools/deploy.sh"
    on:
      all_branches: true
      node: "node"
